### PR TITLE
added shear makers

### PR DESCRIPTION
**Pull request by esheldon**
this code reworks how shear is specified in the config files and how shear PDFs are used in the code

An example config file is here

https://github.com/esheldon/egretsims/blob/master/config/v10test.yaml

### CODE REVIEW

**Comment by beckermr** [comment]
Looks mostly good. I am not sure about requiring a shear maker in order to instantiate a galaxy maker. One could easily want to generate a set of galaxies with no shear. Having to setup a zero shear maker seems a bit overloaded in this case. 

What if we get rid of this interdependence and instead put the dependence in the simpsimmakers?

**Comment by beckermr** [comment]
Also, if calls to shear maker generate a random shear, then this will complicate the drawing of galaxies and shears for ME sims. Better to separate them out.

**Comment by esheldon** [comment]
OK, I'm not sure how to proceed

**Comment by esheldon** [comment]
get_galaxy() is already randomized.  For ME sims we would need a special class anyway that generates a random galaxy, then shears them all the same but puts in different properties for each observation of the galaxy.  Currently this is all in get_galaxy() from a galaxy maker anyway

**Comment by esheldon** [comment]
I don't necessarily disagree this should be in a simpsimmaker but I think the reasons given are not sufficient.  I think the real reason is that the shear field is logically part of a sim not of a galaxy

**Comment by esheldon** [comment]
I think this is probably closer to what you wanted, please have a look when you can

**Comment by beckermr** [comment]
There are still a few things I want to fix. Let's accept this into a branch and then I will merge it later after I do the fixes.

Things to fix:
- [ ] the shear index was added to the meds object data directly, but there is a mechanism in the meds makers to pass extra fields through
- [ ] the shear maker does not accept a seed and is not seed by the simp sim maker
- [ ] galaxy maker base class still has shear stuff in it

About the ME sims. Yes, methods to get multiple different noisy images of the same object are needed. The most transparent way to do this is to have all galaxy makers return object lists (or maybe even lists of object lists for multiple bands).

These would have to mesh with other observing conditions generators. This is all work I want to do, but I have higher priority stuff at the moment.

**Comment by esheldon** [comment]
On 10/30/15, Matthew R. Becker <notifications@github.com> wrote:
> There are still a few things I want to fix. Let's accept this into a branch
> and then I will merge it later after I do the fixes.
>
> Things to fix:
> - [ ] the shear index was added to the meds object data directly, but there
> is a mechanism in the meds makers to pass extra fields through
> - [ ] the shear maker does not accept a seed and is not seed by the simp sim
> maker
> - [ ] galaxy maker base class still has shear stuff in it

what is left?  I do pass in shear, but I think that is required.

>
> About the ME sims. Yes, methods to get multiple different noisy images of
> the same object are needed. The most transparent way to do this is to have
> all galaxy makers return object lists (or maybe even lists of object lists
> for multiple bands).
>
> These would have to mesh with other observing conditions generators. This is
> all work I want to do, but I have higher priority stuff at the moment.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/beckermr/egret/pull/14#issuecomment-152681416


-- 
Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by beckermr** [comment]
Getting back to this. Here are things I was trying to refer to.

1. See this line in the example for how to pass the shear id into the medsmakers

https://github.com/beckermr/egret/blob/master/egret/medsmakers.py#L14

In the simsimmaker, you would put this information here

https://github.com/beckermr/egret/blob/master/egret/simpsimmakers.py#L41

Something like `extra_data = [('shear_id','i8')]`. You can see the psf per epoch extra data passed in there as well. (I also see a bug in my code here. The last one should be a += not an =!)

Once this is done, this line can be removed.

https://github.com/beckermr/egret/pull/14/files#diff-8bec999b75078c12b96de901b488e2baR128

2. Shear makers need to accept seeds and run their own rng. (I do think the rng framework needs work in egret, but this is what I have now.)

3. In your commit, I was wondering about these lines starting here (and the ones above this)

https://github.com/beckermr/egret/pull/14/files#diff-621496e2ea1fce6b40b218302b9a3175R22

It looks like you have leftover code from when the shear maker was instantiated from within the galaxymaker.

**Comment by beckermr** [comment]
I merged this into a branch for some fixes. Closing this PR for now.

**Pull request closed without merging**
